### ISSUE TITLE
ps_load_tables and ps_read_tables failing with class units

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/poissqlite#16]
Error in UseMethod("set_units") : 
  no applicable method for 'set_units' applied to an object of class "character"

**Comment by sebdalgarno** [comment]
tried creating table with INTEGER and TEXT for a column of class 'units'....both can be created but fail to read

**Comment by joethorley** [comment]
OK I'll get on it - Can you provide a [reprex](http://reprex.tidyverse.org/articles/reprex.html) or point me to some code to run to replicate?

**Comment by sebdalgarno** [comment]
Never mind, the issue was that I was saving those 'units' class columns as TEXT, not INTEGER.
ps_load_tables runs fine now.

**Comment by joethorley** [comment]
Yes hard to enforce in SQL

**Comment by sebdalgarno** [comment]
yes I think I was confused because sfc columns are saved as TEXT (at least that's how I do it)

**Comment by joethorley** [comment]
Yes sfc has to be TEXT but a number which may have a units attribute can be stored as INTEGER (if whole numbers) or REAL (if real numbers) or TEXT.

**Comment by joethorley** [comment]
If units attached we probably want to store as REAL
https://sqlite.org/datatype3.html
I could write code to enforce but it would be a bunch of work
