### ISSUE TITLE
ps_strip_columns class option

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/poissqlite#17]
It would be useful to strip all data objects in env based on class not column name.
For example, I may want to strip all sfc columns because it interferes with old analysis scripts (rbind vs. bind_rows being a classic example of problems encountered with sfc and units variables).
Could be an additional argument to `ps_strip_columns`, e.g. `class`. If a column inherits from that class it is removed.

**Comment by sebdalgarno** [comment]
also a strip class function would be useful...e.g. to strip all units classes, or to deactivate all sfc columns.

Perhaps these should be called `ps_env_strip_class`, `ps_env_rm_class`, `ps_env_strip_column`

**Comment by joethorley** [comment]
Better yet `ps_strip_if` could function like `map_if` to strip columns if satisfy a predicate and 
`ps_env_map_df` could take a function such as `ps_strip_if` and apply to all objects in environment. Thoughts?

**Comment by sebdalgarno** [comment]
yes that's much better. 
To remove all sfcs would simply be: `ps_env_map_df(ps_remove_sfcs())`

**Comment by sebdalgarno** [comment]
Do you want me to try and implement in the next couple of weeks?

**Comment by joethorley** [comment]
Yes please

**Comment by joethorley** [comment]
Note this function actually belongs in poisdata as it doesn't directly involve sqlite databases

**Comment by sebdalgarno** [comment]
added `ps_env_map_df()` to poisdata.
I don't think `ps_strip_if()` is necessary as `dplyr::select_if()` will likely suffice.
